/*
 * SPDX-License-Identifier: MIT
 *
 * network_config.h - Hostname and hosts file generation for WSL-For-FreeBSD.
 *
 * Implements the guest-side network configuration logic, mirroring the
 * reference WSL implementation in src/linux/init/config.cpp
 * ConfigInitializeInstance() lines 738-837.
 *
 * When the host sends an Initialize(5) message containing hostname,
 * domainname, and Windows hosts file contents, the guest:
 *   1. Overrides the hostname if [network] hostname is set in /etc/wsl.conf
 *   2. Calls sethostname() to set the kernel hostname
 *   3. Writes /etc/hostname (hostname + newline)
 *   4. Writes /etc/hosts (if generateHosts is true) using the template:
 *      127.0.0.1\tlocalhost
 *      127.0.1.1\t{hostname}.{domain}\t{hostname}
 *      {WindowsHosts contents}
 *      # IPv6 entries...
 *
 * The /etc/resolv.conf generation is handled separately by gns_engine.h
 * in response to NetworkInformation(4) messages, gated by generateResolvConf.
 *
 * Reference: src/linux/init/config.cpp ConfigInitializeInstance()
 *
 * Usage:
 *   #include "network_config.h"
 *
 *   network_apply_hostname(&g_config, &g_wsl_conf);
 *   network_generate_hosts(&g_config, &g_wsl_conf);
 */
#ifndef NETWORK_CONFIG_H
#define NETWORK_CONFIG_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <sys/param.h>  /* MAXHOSTNAMELEN on FreeBSD */

/* ---- Constants matching reference implementation ---- */
#define NETC_HOSTNAME_FILE  "/etc/hostname"
#define NETC_HOSTS_FILE     "/etc/hosts"
#define NETC_FILE_MODE      0644

/* Default hostname fallback (reference: stringshared.h c_defaultHostName) */
#define NETC_DEFAULT_HOSTNAME  "localhost"

/* Default domain name (reference: lxssinstance.cpp LXSS_DOMAIN_NAME_DEFAULT) */
#define NETC_DEFAULT_DOMAIN    "localdomain"

/* Auto-generated file header (reference: lxinitshared.h) */
#define NETC_AUTO_HEADER  "This file was automatically generated by WSL. To prevent automatic generation of this file, add the following entry to /etc/wsl.conf:\n"

/* ---- A4: Sanitize hostname ----
 *
 * Clean a hostname to comply with Linux/FreeBSD hostname rules.
 * Strips invalid characters, enforces single dot, no leading/trailing
 * hyphens/dots, max 64 chars. Falls back to "localhost" if empty.
 *
 * Reference: stringshared.h CleanHostname()
 *
 * Parameters:
 *   dst    - Destination buffer (must be at least 65 bytes)
 *   dst_sz - Size of dst buffer
 *   src    - Source hostname string
 *
 * Returns: pointer to dst on success, NULL on error. */
static inline char *network_clean_hostname(char *dst, size_t dst_sz,
                                            const char *src)
{
    if (!dst || dst_sz == 0) return NULL;

    if (!src || !*src) {
        strncpy(dst, NETC_DEFAULT_HOSTNAME, dst_sz - 1);
        dst[dst_sz - 1] = '\0';
        return dst;
    }

    size_t j = 0;
    int saw_dot = 0;
    for (size_t i = 0; src[i] && j < dst_sz - 1; i++) {
        char c = src[i];
        /* Valid hostname chars: alphanumeric, hyphen, dot */
        if (isalnum((unsigned char)c) || c == '-' || c == '.') {
            /* Enforce single dot — once a dot is seen, skip all subsequent dots */
            if (c == '.') {
                if (saw_dot) continue;
                saw_dot = 1;
            }
            /* Skip leading hyphens/dots */
            if (j == 0 && (c == '-' || c == '.')) continue;
            dst[j++] = c;
        }
        /* Invalid chars are silently stripped */
    }
    dst[j] = '\0';

    /* Strip trailing hyphens/dots */
    while (j > 0 && (dst[j-1] == '-' || dst[j-1] == '.')) {
        dst[--j] = '\0';
    }

    /* Max 64 chars (reference: HOST_NAME_MAX) */
    if (j > 64) {
        dst[64] = '\0';
    }

    /* Fallback to default if empty */
    if (j == 0) {
        strncpy(dst, NETC_DEFAULT_HOSTNAME, dst_sz - 1);
        dst[dst_sz - 1] = '\0';
    }

    return dst;
}

/* ---- A4: Set guest hostname ----
 *
 * Applies the hostname from the Initialize(5) message, optionally
 * overridden by [network] hostname from /etc/wsl.conf.
 * Calls sethostname() and writes /etc/hostname.
 *
 * Parameters:
 *   hostname     - Hostname from Initialize(5) message (may be NULL/empty)
 *   conf_hostname - Override from [network] hostname in wsl.conf (may be NULL)
 *
 * Returns: 0 on success, -1 on error.
 *
 * Reference: config.cpp lines 738-808 */
static inline int network_apply_hostname(const char *hostname,
                                          const char *conf_hostname)
{
    /* Determine which hostname to use:
     * - [network] hostname in wsl.conf takes priority (if set)
     * - Otherwise use the hostname from Initialize(5) message
     * - Fallback to "localhost" */
    const char *raw = NULL;
    if (conf_hostname && conf_hostname[0] != '\0') {
        raw = conf_hostname;
        printf("[net] using wsl.conf hostname: %s\n", raw);
    } else if (hostname && hostname[0] != '\0') {
        raw = hostname;
        printf("[net] using host-provided hostname: %s\n", raw);
    } else {
        raw = NETC_DEFAULT_HOSTNAME;
        printf("[net] using default hostname: %s\n", raw);
    }

    /* Sanitize the hostname */
    char clean[65];
    network_clean_hostname(clean, sizeof(clean), raw);

    /* Call sethostname() — set kernel hostname */
    if (sethostname(clean, strlen(clean)) < 0) {
        fprintf(stderr, "[net] sethostname('%s'): %s\n", clean, strerror(errno));
        /* Fallback to "localhost" on failure */
        if (strcmp(clean, NETC_DEFAULT_HOSTNAME) != 0) {
            if (sethostname(NETC_DEFAULT_HOSTNAME,
                            strlen(NETC_DEFAULT_HOSTNAME)) < 0) {
                fprintf(stderr, "[net] sethostname fallback '%s': %s\n",
                        NETC_DEFAULT_HOSTNAME, strerror(errno));
            } else {
                printf("[net] sethostname fallback to '%s'\n", NETC_DEFAULT_HOSTNAME);
            }
        }
    } else {
        printf("[net] sethostname('%s') OK\n", clean);
    }

    /* Set NAME environment variable (reference: config.cpp line 772) */
    setenv("NAME", clean, 1);

    /* Write /etc/hostname (hostname + newline) */
    FILE *fp = fopen(NETC_HOSTNAME_FILE, "w");
    if (!fp) {
        fprintf(stderr, "[net] fopen %s: %s\n", NETC_HOSTNAME_FILE, strerror(errno));
        return -1;
    }
    fprintf(fp, "%s\n", clean);
    fclose(fp);
    printf("[net] wrote %s to %s\n", clean, NETC_HOSTNAME_FILE);

    return 0;
}

/* ---- A4: Generate /etc/hosts ----
 *
 * Generates /etc/hosts using the reference WSL template:
 *   # Auto-generated header
 *   # [network]
 *   # generateHosts = false
 *   127.0.0.1\tlocalhost
 *   127.0.1.1\t{hostname}.{domain}\t{hostname}
 *   {WindowsHosts contents}
 *   # IPv6 entries...
 *
 * Parameters:
 *   hostname       - Hostname from Initialize(5) message
 *   domainname     - Domain name from Initialize(5) message
 *   windows_hosts  - Contents of Windows hosts file (may be NULL/empty)
 *   generate_hosts - 1 if [network] generateHosts is true, 0 to skip
 *
 * Returns: 0 on success, -1 on error, 1 if skipped.
 *
 * Reference: config.cpp lines 811-837 */
static inline int network_generate_hosts(const char *hostname,
                                          const char *domainname,
                                          const char *windows_hosts,
                                          int generate_hosts)
{
    if (!generate_hosts) {
        printf("[net] generateHosts=false, skipping /etc/hosts generation\n");
        return 1;
    }

    /* Sanitize hostname for the hosts file */
    char clean_host[65];
    network_clean_hostname(clean_host, sizeof(clean_host), hostname);

    /* Determine domain name */
    const char *domain = (domainname && domainname[0] != '\0')
                         ? domainname : NETC_DEFAULT_DOMAIN;

    FILE *fp = fopen(NETC_HOSTS_FILE, "w");
    if (!fp) {
        fprintf(stderr, "[net] fopen %s: %s\n", NETC_HOSTS_FILE, strerror(errno));
        return -1;
    }

    /* Write auto-generated header */
    fprintf(fp, "%s", NETC_AUTO_HEADER);
    fprintf(fp, "# [network]\n");
    fprintf(fp, "# generateHosts = false\n");
    fprintf(fp, "\n");

    /* Localhost entry */
    fprintf(fp, "127.0.0.1\tlocalhost\n");

    /* Host entry: 127.0.1.1\t{hostname}.{domain}\t{hostname} */
    fprintf(fp, "127.0.1.1\t%s.%s\t%s\n", clean_host, domain, clean_host);

    /* Append Windows hosts file contents (if any) */
    if (windows_hosts && windows_hosts[0] != '\0') {
        fprintf(fp, "\n# Windows hosts file entries\n");
        fputs(windows_hosts, fp);
        /* Ensure trailing newline */
        size_t wh_len = strlen(windows_hosts);
        if (wh_len > 0 && windows_hosts[wh_len - 1] != '\n') {
            fputc('\n', fp);
        }
    }

    /* IPv6 entries (reference: config.cpp HostsFileFormatString) */
    fprintf(fp, "\n# The following lines are desirable for IPv6 capable hosts\n");
    fprintf(fp, "::1     ip6-localhost ip6-loopback\n");
    fprintf(fp, "fe00::0 ip6-localnet\n");
    fprintf(fp, "ff00::0 ip6-mcastprefix\n");
    fprintf(fp, "ff02::1 ip6-allnodes\n");
    fprintf(fp, "ff02::2 ip6-allrouters\n");

    fclose(fp);
    printf("[net] wrote %s (host=%s, domain=%s)\n",
           NETC_HOSTS_FILE, clean_host, domain);

    return 0;
}

/* ---- A4: Set domain name ----
 *
 * Calls setdomainname() with the domain from the Initialize(5) message.
 *
 * Parameters:
 *   domainname - Domain name string (may be NULL/empty)
 *
 * Returns: 0 on success, -1 on error.
 *
 * Reference: config.cpp lines 781-784 */
static inline int network_apply_domainname(const char *domainname)
{
    if (!domainname || domainname[0] == '\0') {
        return 0;  /* No domain to set */
    }

    if (setdomainname(domainname, strlen(domainname)) < 0) {
        fprintf(stderr, "[net] setdomainname('%s'): %s\n",
                domainname, strerror(errno));
        return -1;
    }
    printf("[net] setdomainname('%s') OK\n", domainname);
    return 0;
}

#endif /* NETWORK_CONFIG_H */
